### ISSUE TITLE
Läuft unter Contao 4

### ISSUE THREAD

**Issue by k-webdesign** [christianbarkowsky/tabcontrol#23]
Hi Christian,

ich wollte nur Bescheid geben, dass die Erweiterung unter Contao 4 läuft. Hab es nicht auf Herz und Nieren geprüft, aber das manuelle Nachinstallieren geht und im Frontend läuft es auch ohne Fehler.

**Comment by christianbarkowsky** [comment]
👍

**Comment by Jaaaan** [comment]
Jedoch nicht in der Managed Edition: 
![grafik](https://user-images.githubusercontent.com/16544159/29840265-b2bbebec-8d01-11e7-8283-c5538ac5d050.png)

Vielleicht hilft #24

**Comment by k-webdesign** [comment]
Doch, ich hab es in der Managed Edition getestet. Über Composer kann man es, soweit ich weiß, noch nicht installieren, daher lief mein Test unter einer manuellen Installation der Extension

**Comment by christianbarkowsky** [comment]
tHx @k-webdesign 
wird erledigt.

**Comment by Jaaaan** [comment]
@christianbarkowsky da die Freigabe für Contao 4 in der `composer.json` fehlt? 

Vielleicht gibt es [hier](https://github.com/contao-community-alliance/composer-plugin/blob/master/README.md) etwas Informatives, falls du es nicht schon kennst. ;-)

**Comment by cliffparnitzky** [comment]
closed with 7b90742dc7d8370ac156bc65ed384f10bf0099d6
