### ISSUE TITLE
ce_ im Backend nicht zu finden

### ISSUE THREAD

**Issue by operatorone** [christianbarkowsky/tabcontrol#26]
Hallo, 

ich habe gerade die Erweiterung über den Contao Manager in eine 4.4.12 Instanz installiert. Leider erscheint das Tab-Inhaltselement nicht in der Liste der auswählbaren Inhaltselemente. Ich habe nach der Insatllation nochmals de Cache geleert. Beim Datenbank-Update wurde mir keine mögliche Aktion angezeigt. Woran könnte es noch liegen, dass ich die Inhaltselemente nicht sehe?

Viele Grüße,
operatorone

**Comment by operatorone** [comment]
Sorry. ich war zu blind. Ich habe nach einer eigenen Gruppe gesucht und der Tab heißt ja "Reiter". Habs gefunden! Danke für die tolle Erweiterung.

**Comment by christianbarkowsky** [comment]
@operatorone :)
