### ISSUE TITLE
tabcontrolJS Hook

### ISSUE THREAD

**Issue by reluem** [christianbarkowsky/tabcontrol#28]
how do I use the tabcontrolJS Hook?
I tried referencing my custom JS file in my config.php, but I always get an array warning.

I don't even need any tabcontrol JS invoked, since it is already loaded within my TL_JAVASCRIPT on default.

thank you!

**Comment by christianbarkowsky** [comment]
Hey @reluem ... i have not used this hook for years. Hmmm, i have to see.

**Comment by reluem** [comment]
Hey, in the meantime I used the a frontend hook to remove the JS. This works quite fine for me :)

**Comment by christianbarkowsky** [comment]
would you like to show me your own script? @reluem

**Comment by reluem** [comment]
Not fancy / following best practice in any way…

https://github.com/reluem/contao-UIkit/blob/eca36cf2a988ac753de65638c4ddeea94ceadd72/src/Resources/contao/classes/integrations/UIkitclassesHook.php#L70

I unset the JS from $GLOBALS in my Controller class using the parseTemplate Hook, which I‘m calling anyway for another integration.

This works fine, but probably there‘s a better solution ;)


https://github.com/reluem/contao-UIkit/blob/eca36cf2a988ac753de65638c4ddeea94ceadd72/src/Resources/contao/classes/integrations/UIkitclassesHook.php#L70
https://github.com/reluem/contao-UIkit/blob/eca36cf2a988ac753de65638c4ddeea94ceadd72/src/Resources/contao/classes/integrations/UIkitclassesHook.php#L70
https://github.com/reluem/contao-UIkit/blob/eca36cf2a988ac753de65638c4ddeea94ceadd72/src/Resources/contao/classes/integrations/UIkitclassesHook.php#L70

**Comment by christianbarkowsky** [comment]
Ok. Fine. Next i will build a jquery version.
