### ISSUE TITLE
Contao 4 / mate-Theme Problem

### ISSUE THREAD

**Issue by JensOnnen** [christianbarkowsky/tabcontrol#35]
Moin,
habe TabControl unter 4.7 und dem mate-Theme installiert, aber leider sehe ich keine Tabs, sondern nur den "rohen" Text. Aufbau erfolgt lt. Screenshots. Vielleicht liegt es daran, dass ich "MultiColumnWizard" nicht installieren konnte (Fehlermeldung)? Bin neu bei Contao, hoffe aber auf eine nette Hilfestellung :-)
Gruß, Jens.

**Comment by Monsterdog2k** [comment]
Hey,
ich bin zwar nicht der Entwickler aber hast du eine entsprechende CSS-Datei eingebunden? Es wird von Hause aus keine eigene CSS-Datei für das Frontend mitgebracht.
Schöne Grüße
Stefan

**Comment by christianbarkowsky** [comment]
Hier kannst du z.b. das CSS kopieren >> [https://brkwsky.de/tabcontrol-contao.html](https://brkwsky.de/tabcontrol-contao.html)

@JensOnnen & @Monsterdog2k ... wäre es besser ein CSS  mitzuliefern?

**Comment by JensOnnen** [comment]
Hallo,

danke für die Antwort, aber (mal ganz doof gefragt): wie kopiere ich denn
von der Seite das CSS? Ich sehe nur die entsprechenden Verweise im
Quellcode... Wäre super, wenn ich diese schönen Tabs auch benutzen könnte...

Danke & tschüß,

Jens.


Am Mo., 20. Mai 2019 um 10:50 Uhr schrieb Christian Barkowsky <
notifications@github.com>:

**Comment by christianbarkowsky** [comment]
@JensOnnen ganz einfach ... nutze die Entwickler-Werkzeuge vom Browser ... da kannst du dir dann das entsprechende Element auswählen und die Styles ansehen.
